[build-system]
requires = ["poetry-core>=1.9.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "celestialvault"
version = "1.0.1"
description = "A Python package for managing celestial data."
readme = "README.md"
authors = ["Mr.Xiaotian <mingxiaomingtian@gmail.com>"]
license = "MIT"
homepage = "https://github.com/Mr-xiaotian/CelestialVault"
repository = "https://github.com/Mr-xiaotian/CelestialVault"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]
packages = [{ include = "celestialvault", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.10"
numpy = ">=1.26"
pandas = ">=2.2"
mpmath = ">=1.3"
regex = ">=2023.0"
bidict = ">=0.22"
reedsolo = ">=1.7"
charset-normalizer = ">=3.3"
pillow = ">=10.0"
pillow-heif = ">=0.15"
rarfile = ">=4.1"
py7zr = ">=0.20"
httpx = ">=0.27"
requests = ">=2.32"
tqdm = ">=4.66"
loguru = ">=0.7"
networkx = ">=3.2"
beautifulsoup4 = ">=4.12"
matplotlib = ">=3.9.1"

[tool.poetry.group.dev.dependencies]
# scikit-image = ">=0.24"  # Python 3.14 不兼容（需要时再开）
pytest = "^8.0"

[tool.poetry.scripts]
# celestial-vault = "celestialvault.cli:main"
